export const SET_UPCOMING_SESSIONS = 'SET_UPCOMING_SESSIONS'
export const SET_PENDING_REQUESTS = 'SET_PENDING_REQUESTS'
export const SET_PAST_SESSIONS = 'SET_PAST_SESSIONS'
export const ADD_PENDING_SESSION = 'ADD_PENDING_SESSION'